name: dynamic_form_fields
description: A Flutter package for creating dynamic form fields with support for various field types and backend integration
version: 0.0.1
homepage:  https://github.com/anwarsafy/dynamic_form_fields
repository: https://github.com/anwarsafy/dynamic_form_fields
issue_tracker: https://github.com/anwarsafy/dynamic_form_fields/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
